SELECT    
     v_GS_SYSTEM.Name0,
     v_GS_OPERATING_SYSTEM.Caption0,
     v_GS_OPERATING_SYSTEM.CSDVersion0,
     v_GS_NETWORK_ADAPTER_CONFIGUR.IPAddress0
FROM        
     v_GS_SYSTEM
JOIN
     v_GS_OPERATING_SYSTEM ON v_GS_SYSTEM.ResourceID = v_GS_OPERATING_SYSTEM.ResourceID
JOIN
     v_GS_NETWORK_ADAPTER_CONFIGUR ON v_GS_OPERATING_SYSTEM.ResourceID = v_GS_NETWORK_ADAPTER_CONFIGUR.ResourceID
WHERE
     v_GS_NETWORK_ADAPTER_CONFIGUR.IPAddress0 is not null
